sudo: required
language: go
go:
- '1.7'
before_install:
- go get github.com/golang/lint/golint
script:
- golint *.go
- go get
- go build *.go
services:
- docker
deploy:
  provider: script
  script: make travis
  on:
    tags: true
env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}
  - secure: TYxN00rNE1N82x88GrDfS64ZG8T9r9haXpzcqGmPLXmJWYgQhpes1O9cyqBj+pVuUG32Mar1SjQVt4tB+ZmHsekWpuWb38J9VqWH9Z2x9hVLyIXPfr4J4njMd5Ao/EwN2vZ19DD2B46sySNBhkRaYGTVrcw72THIoYkexvYPgezG2givqQJU4DVwsVuhsBh5eSmju+2ECBPi4KYca9YdEH0bQwk4Vi7PkQnleuSI1ufZ0bYL3InxIQxPakf+hAZVitMldvWnIvRFW+9IH49NpytcTsemTIlVVK+egA+2hxKyX1OrnMXzqZaoGLF6aWQml8kNlH1rSP2QZOs8X6W3ZOcbjDEkiwvAlaXPvOErMr7R+DvCCFD5rbOJ/VR1Ya9za0d++CnScmKq1cXLZDiDl8AYAESxYdatqfKz+Cgk3HBPp+OFSjzA4243ix/QUGO4hkZXUZuynpjgKfgGYPl8BwB8XnKAiyyTMxVikMUNxkwdXs95LMEsqN9i/cLNKPT4l0gdDfXQX0rI5HIN1+K0DtAJxsoaMARfVwJdG28v+utjEavYyW9X8oA0jHRXj7CqEz68TmE1Dy4nZGBjaQesm055+01ri4XyVLz6TVesGDUk9a3/iaqFv6DMq1K1lI0h5UAKG81lyTjxUVDrUU1zZviGqApsni3M9UoH+Y7bXL0=
  - secure: im0x4qsLPztY/rD0SHgKbuZ3dpHRaNQMGR52i0YWBCZ04s7qqtaRyFyiELclSFNIoSNXetZ5o+oUs1x2yIXRVGEHdAMxKcgoiWwoVaccuFoyB6yVJZwO+tAp86b396Q3qsiX1mXyd6plZqeCMYgZmgKApjSC276uREE9Bna9S/NE+oPaAMU5uXtVd62QVyIgwcDLp/8+E9XPI6+5Wio6vPlTcFM+Jmt+MkBSKqKLjUUk7xpM+aqn9si8R54VmwQuXDDTeBguvE1Qo2m6o5sevyGqjCUHrFbAOee/ovrew8EeKv/lKIghEN9LEifq+5Z1mQe7Ks4P4l5Hf3Y3/baMuL1v+44X8BGReRM+F5bWKt7M0G0WwbHY7Lh5GFCy/Rf/q0CKx6w0IJP2tN9g8ODM0Yxzk2AaUNOf7I755yy5kISRK7y8pP2yibkK5jtKai1TAkhO8iM/CFCV59QyUL6qPry8TiYFLjRXX2QmycTNhikzkvWZaxq9PNjK4lJZ+d/qmoQ4J8QKsYjdSrzWI1nCvYHO6K1RRgJUSbZ0uO0DDzPMWJyjVGIL4oIyuP0iJhDkZwE4xY/wixa7cY7/hUa9n/Jd4ZBGfOyCFobfWpb9/oyqu507ltMSswXjmoB4wYMQuX4fIlYbrYBtznZOqbmouAW82Ke1R0tfHNvAFfIVhzw=
  - secure: Zk/fanv6vHNN2edB0SR7lTNK61gmys2clkgS6tX+eBNom5sP7IFZXzpWq2JE5kL2yYdDYRGNIx+Tf0iv2ayejfm9Zwp/vTNKvZwDFF4nSMeXLm5UcjmO1kBI/XWXDZHn+fuEVsmrRgEU5P6TYQqNt4BP9TlzLZytiSHS1JcWrzTYret2J1h5efgkUb0JKYA0b5eIdCqFC+n3iwAZof3C3ZzrvbkBTCmvbMwPUo3X+eQhsLYfiVUJnAAM+A3GngSN4QQpRCKrlGe9jxeTSot0a5yZMD/VENzANpnLuCfEhtZVeRzx5lFytRX7vnzJZ75QtoHzwxM7Qg+KxnkauBT1ZtRs+Evlo5nSFPknAOjx826ks4PMrHL036mo8wr8YVLQlxLZDs96MRmSZel9P/PI1bj5Ep4hM3y3AeFt++Z3dMmx5aTud5WEhPO14KwOAeQ+DAdfqZD1IfFyWJXcEtOXgAJcqzc7uaXDnETDZI3ddB6zcluJuuoymsoOSb+Hwe0jV58ayEnIN+1cNratNPn2C5zTtMfwr6GIQjCAITZwxfpkci03c6NhLvOGFxMwWz7lOUIVlxm38NcFHjDeCou2VCxu/+d6KfkSWkNlSDdZKn+2zGYL5vlPa+M5Gx9E7OYy6648ttsIhg/xnBzqabbpIBoWQG0Lc0yEb/wIfTC/yIs=
